services:
  - type: web
    name: urbanperu-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 12h
      - key: DASHBOARD_USER
        sync: false
      - key: DASHBOARD_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DIRECCION_LOCAL
        sync: false
